version: '3.8'

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  node-exporter:
    # image: prom/node-exporter
    # volumes:
    #   - /proc:/host/proc:ro
    #   - /sys:/host/sys:ro
    #   - /:/rootfs:ro
    # command:
    #   - '--path.procfs=/host/proc'
    #   # - '--path.rootfs=/rootfs'
    #   - '--path.sysfs=/host/sys'
    #   # - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    #   - --collector.filesystem.ignored-mount-points
    #   - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
    # update to latest
    # https://github.com/prometheus/node_exporter
    restart: unless-stopped
    image: quay.io/prometheus/node-exporter
    network_mode: host
    pid: host
    volumes:
      - '/:/host:ro,rslave'
    command:
      - '--path.rootfs=/host'
      - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/)
      - --collector.processes
      - --collector.systemd
    expose:
      - 9100
    deploy:
      mode: global

  # https://github.com/nginxinc/nginx-prometheus-exporter
  # docker run -p 9113:9113 nginx/nginx-prometheus-exporter:0.10.0 -nginx.scrape-uri=http://<nginx>:8080/stub_status
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    restart: unless-stopped
    command:
      - '-nginx.scrape-uri=http://host.docker.internal/stub_status'
      # - '-nginx.scrape-uri=https://xxxxx.xxx/stub_status'
    expose:
      - 9113
    extra_hosts:
     - "host.docker.internal:host-gateway"
    deploy:
      mode: global

  cadvisor:
    image: google/cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080
    deploy:
      mode: global
  
  prometheus:
    image: prom/prometheus
    # err="open /prometheus/queries.active: permission denied" #5976
    # https://github.com/prometheus/prometheus/issues/5976#issuecomment-540457847
    user: root
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      # Allow relative URL in web.external-url #1583 
      # https://github.com/prometheus/prometheus/issues/1583#issuecomment-395617142
      - '--web.external-url=http://dummy/prometheus'
      - '--web.route-prefix=/prometheus'
    # expose:
    #   - 9090
    ports:
      - 127.0.0.1:9090:9090
    # From inside of a Docker container, how do I connect to the localhost of the machine?
    # https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana
    # user: '472'
    # err="open /prometheus/queries.active: permission denied" #5976
    # https://github.com/prometheus/prometheus/issues/5976#issuecomment-540457847
    user: root
    restart: unless-stopped
    environment: {}
      # Alerting problem: error message “error=“context deadline exceeded”
      # https://community.grafana.com/t/alerting-problem-error-message-error-context-deadline-exceeded/27791/4
      # GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - .env.grafana
    ports:
      # security: Docker EXPOSE a port only to Host
      # https://stackoverflow.com/questions/22100587/docker-expose-a-port-only-to-host
      - 127.0.0.1:4000:3000
    depends_on:
      - prometheus
