global:
  scrape_interval: 10s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
      - targets:
        - localhost:9090

  - job_name: "node"
    static_configs:
      - targets:
        - node-exporter:9100

  # https://grafana.com/grafana/dashboards/12745-pm2-dashboard/
  # https://github.com/saikatharryc/pm2-prometheus-exporter
  - job_name: pm2-metrics
    static_configs:
      - targets:
        - localhost:9209
        - host.docker.internal:9209

  # Collect Docker metrics with Prometheus
  # https://docs.docker.com/config/daemon/prometheus/
  # https://grafana.com/grafana/dashboards/10619-docker-host-container-overview/
  - job_name: 'docker'
    static_configs:
      - targets:
        - localhost:9323
        - host.docker.internal:9323
