global:
  scrape_interval: 15s
  scrape_timeout: 15s

scrape_configs:
  - job_name: "prometheus"
    metrics_path: /prometheus/metrics
    static_configs:
      - targets:
        - prometheus:9090

  - job_name: cadvisor
    static_configs:
      - targets:
        - cadvisor:8080

  - job_name: "node"
    static_configs:
      - targets:
        - node-exporter:9100

  # https://grafana.com/grafana/dashboards/12745-pm2-dashboard/
  # https://github.com/saikatharryc/pm2-prometheus-exporter
  - job_name: pm2-metrics
    static_configs:
      - targets:
        - host.docker.internal:9209

  # Collect Docker metrics with Prometheus
  # https://docs.docker.com/config/daemon/prometheus/
  # https://grafana.com/grafana/dashboards/10619-docker-host-container-overview/
  - job_name: 'docker'
    static_configs:
      - targets:
        - host.docker.internal:9323

  # https://github.com/nginxinc/nginx-prometheus-exporter
  # https://grafana.com/grafana/dashboards/14900-nginx/
  - job_name: nginx-metrics
    static_configs:
      - targets:
        - nginx-exporter:9113
