version: "3"
services:
  rabbitmq:
    # image: "fritx/rabbitmq-delayed:3"
    image: "fritx/rabbitmq-delayed:3-alpine"
    # build:
    #   context: .
    restart: unless-stopped
    ports:
      # security: Docker EXPOSE a port only to Host
      # https://stackoverflow.com/questions/22100587/docker-expose-a-port-only-to-host
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
    env_file:
      - .env
volumes:
  rabbitmq_data:
