version: '3'
services:
  nsqd:
    image: nsqio/nsq
    command: /nsqd
    ports:
      - "4150:4150"
      - "4151:4151"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --nsqd-http-address=nsqd:4151
    ports:
      - "4171:4171"
