version: "3"
services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      # security: Docker EXPOSE a port only to Host
      # https://stackoverflow.com/questions/22100587/docker-expose-a-port-only-to-host
      - "127.0.0.1:6379:6379"
    volumes:
      - "redis_data:/data"
volumes:
  redis_data:
